server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: ai-agent-demo
  
  # 静态资源配置
  web:
    resources:
      static-locations: classpath:/static/
  
  # 日志配置
  logging:
    level:
      agent: DEBUG
      tools: DEBUG
      controller: DEBUG
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# 自定义配置
app:
  agent:
    # 模型配置
    model:
      name: qwen-plus
      temperature: 0.7
      max-tokens: 1000
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
    
    # 并发配置
    max-concurrent-tasks: 10
    task-timeout-seconds: 300
    
    # 聊天配置
    max-messages: 10
    max-tool-calls-per-request: 5
    
    # 功能开关
    enable-websocket: true
    enable-caching: true 